-- Craft-owned standard-operation library. This is distinct from GBOP tree entries.
CREATE TABLE IF NOT EXISTS `workmanship_craft_standard_operations` (
  `gid` CHAR(36) PRIMARY KEY,
  `display_id` VARCHAR(64) NOT NULL DEFAULT '',
  `code` VARCHAR(255) NOT NULL DEFAULT '',
  `name` VARCHAR(512) NOT NULL DEFAULT '',
  `standard_time` DOUBLE NOT NULL DEFAULT 0,
  `importance` VARCHAR(255) NOT NULL DEFAULT '',
  `description` VARCHAR(2048) NOT NULL DEFAULT '',
  `level` VARCHAR(255) NOT NULL DEFAULT '',
  `vpps_attr` VARCHAR(255) NOT NULL DEFAULT '',
  `vpps` TEXT NULL,
  `vpps_desc` VARCHAR(512) NOT NULL DEFAULT '',
  `torque_importance` VARCHAR(255) NOT NULL DEFAULT '',
  `vehicle_model` VARCHAR(255) NOT NULL DEFAULT '',
  `parent_vpps` VARCHAR(255) NOT NULL DEFAULT '',
  `steps` JSON NOT NULL,
  `required_tools` JSON NOT NULL,
  `parameters` JSON NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `share_scope` VARCHAR(32) NOT NULL DEFAULT 'team',
  `version` BIGINT NOT NULL DEFAULT 1,
  `created_by` VARCHAR(255) NOT NULL DEFAULT '',
  `team_id` VARCHAR(255) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  INDEX `idx_standard_operations_code` (`code`),
  INDEX `idx_standard_operations_scope` (`team_id`, `created_by`, `share_scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
