name: Test Build
on:
  push:
    branches: [build-test]

jobs:
  test:
    runs-on: [self-hosted, test-server]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: devteam/workmanship-web
          ref: test
          path: workmanship-web
          token: ${{ secrets.CROSS_REPO_TOKEN }}

      - name: Build
        shell: cmd
        working-directory: workmanship-web
        run: |
          where node
          if exist "node_modules" rmdir /s /q node_modules
          npm ci --ignore-scripts
          npm run build:web
        env:
          NODE_OPTIONS: --max-old-space-size=4096
