name: Test PATH
on:
  push:
    branches: [path-test]

jobs:
  test:
    runs-on: [self-hosted, test-server]
    steps:
      - name: Test tools
        shell: cmd
        run: |
          where node
          where git
          where npm
          where python
          echo ALL OK
