CREATE TABLE IF NOT EXISTS workmanship_base_consumer_delegations (
  delegation_id VARCHAR(256) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  delegated_by VARCHAR(256) NOT NULL,
  actor_user_id VARCHAR(256) NULL,
  actor_service_id VARCHAR(256) NULL,
  tenant_id VARCHAR(256) NOT NULL,
  consumer_type VARCHAR(32) NOT NULL,
  consumer_id VARCHAR(256) NOT NULL,
  consumer_version VARCHAR(128) NULL,
  installation_id VARCHAR(256) NULL,
  mount_session_id VARCHAR(256) NULL,
  agent_run_id VARCHAR(256) NULL,
  catalog_release VARCHAR(128) NOT NULL,
  capability_scopes_json JSON NOT NULL,
  resource_scopes_json JSON NOT NULL,
  data_scopes_json JSON NOT NULL,
  maximum_automation_level VARCHAR(4) NOT NULL,
  authentication_method VARCHAR(64) NOT NULL,
  authenticated_at DATETIME(6) NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  revoked_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (delegation_id),
  UNIQUE KEY uq_base_consumer_delegation_token_hash (token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
