"""Independent reviewed decisions for the pinned Task 3B.3b baseline."""
from __future__ import annotations

from typing import Any


BASELINE_REVISION = "2c17617c28e0bed2411763e9ae5520128f2804e0"

MIGRATIONS: dict[tuple[str, str], dict[str, str]] = {
    ("DELETE", "/api/knowledges/{dynamic}"): {"operation": "knowledge.delete", "target": "knowledge.entry.change.apply.atomic.entries_delete@1", "request": "gid -> {gid}", "response": "discard provider projection and preserve {success:true}", "provider_source": "plugins/knowledge/knowledge_backend/api/knowledge_entries_legacy.py", "provider_needle": "entries.delete"},
    ("GET", "/api/knowledge/entries"): {"operation": "knowledge.search", "target": "knowledge.search@1", "request": "list_gid -> bounded search with content", "response": "provider items -> legacy data array", "provider_source": "plugins/knowledge/knowledge_backend/api/knowledge_entries_legacy.py", "provider_needle": '"knowledge.search"'},
    ("GET", "/api/knowledges/{dynamic}"): {"operation": "knowledge.get", "target": "knowledge.get@1", "request": "gid -> {gid}", "response": "provider record -> legacy data record", "provider_source": "plugins/knowledge/knowledge_backend/api/knowledge_entries_legacy.py", "provider_needle": '"knowledge.get"'},
    ("PATCH", "/api/knowledges/{dynamic}"): {"operation": "knowledge.update", "target": "knowledge.entry.change.apply.atomic.entries_update@1", "request": "gid plus patch -> {gid,updates}", "response": "discard provider projection and preserve {success:true}", "provider_source": "plugins/knowledge/knowledge_backend/api/knowledge_entries_legacy.py", "provider_needle": "entries.update"},
    ("POST", "/api/knowledges"): {"operation": "knowledge.create", "target": "knowledge.entry.change.apply.atomic.entries_create@1", "request": "legacy record -> atomic record payload", "response": "provider gid projection -> legacy data", "provider_source": "plugins/knowledge/knowledge_backend/api/knowledge_entries_legacy.py", "provider_needle": "entries.create"},
    ("PUT", "/api/knowledge/entries"): {"operation": "knowledge.update", "target": "knowledge.entry.change.apply.atomic.entries_update@1", "request": "body gid plus fields -> {gid,updates}", "response": "discard provider projection and preserve {success:true}", "provider_source": "plugins/knowledge/knowledge_backend/api/knowledge_entries_legacy.py", "provider_needle": "entries.update"},
    ("PUT", "/api/knowledges/{dynamic}"): {"operation": "knowledge.update", "target": "knowledge.entry.change.apply.atomic.entries_update@1", "request": "gid plus body -> {gid,updates}", "response": "discard provider projection and preserve {success:true}", "provider_source": "plugins/knowledge/knowledge_backend/api/knowledge_entries_legacy.py", "provider_needle": "entries.update"},
    ("GET", "/api/tasks/{dynamic}/entries"): {"operation": "project.itemEntries.get", "target": "project.list.read.atomic.item_entries_get@1", "request": "task gid -> {arguments:{item_type:'task',item_gid}}", "response": "provider entries -> legacy data array", "provider_source": "plugins/project_management/project_management_backend/capabilities/reviewed.py", "provider_needle": "payload.get(\"arguments\", payload)"},
    ("PUT", "/api/tasks/{dynamic}/entries"): {"operation": "project.itemEntries.replace", "target": "project.list.change.apply.atomic.item_entries_replace@1", "request": "task gid and entries -> {arguments:{item_type,item_gid,entries}}", "response": "provider replace projection -> legacy data", "provider_source": "plugins/project_management/project_management_backend/capabilities/reviewed.py", "provider_needle": "payload.get(\"arguments\", payload)"},
    ("PUT", "/api/tasks"): {"operation": "project.task.update", "target": "project.task.change.apply.atomic.tasks_update@1", "request": "body gid plus fields -> {arguments:{gid,updates}}", "response": "provider update projection -> legacy data", "provider_source": "plugins/project_management/project_management_backend/capabilities/reviewed.py", "provider_needle": "payload.get(\"arguments\", payload)"},
    ("PUT", "/api/issues"): {"operation": "project.issue.update", "target": "project.issue.change.apply.atomic.issues_update@1", "request": "body gid plus fields -> {arguments:{gid,updates}}", "response": "provider update projection -> legacy data", "provider_source": "plugins/project_management/project_management_backend/capabilities/reviewed.py", "provider_needle": "payload.get(\"arguments\", payload)"},
    ("GET", "/api/views"): {"operation": "base.savedViews.search", "target": "base.saved_view.search@1", "request": "module/list_gid -> closed aggregate scope query", "response": "provider views -> legacy saved-view array", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.saved_view.search": _saved_view_search'},
    ("POST", "/api/views"): {"operation": "base.savedViews.create", "target": "base.saved_view.create@1", "request": "saved-view fields -> closed create command with idempotency", "response": "provider view envelope -> saved-view projection", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.saved_view.create": _saved_view_create'},
    ("PATCH", "/api/views/{dynamic}"): {"operation": "base.savedViews.update", "target": "base.saved_view.update@1", "request": "view gid/revision/config -> closed update command with idempotency", "response": "provider view envelope -> saved-view projection", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.saved_view.update": _saved_view_update'},
    ("POST", "/api/views/{dynamic}/copy"): {"operation": "base.savedViews.copy", "target": "base.saved_view.copy@1", "request": "view gid/name -> closed copy command with idempotency", "response": "provider view envelope -> copied saved-view projection", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.saved_view.copy": _saved_view_copy'},
    ("DELETE", "/api/views/{dynamic}"): {"operation": "base.savedViews.delete", "target": "base.saved_view.delete@1", "request": "view gid/revision -> closed tombstone command with idempotency", "response": "provider view envelope -> deleted saved-view projection", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.saved_view.delete": _saved_view_delete'},
    ("GET", "/api/self_ann/{dynamic}"): {"operation": "base.annotations.get", "target": "base.self_annotation.record.get@1", "request": "item gid -> closed self-only record query", "response": "annotation envelope -> closed annotation projection", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.self_annotation.record.get": _annotation_get'},
    ("GET", "/api/self_ann/list"): {"operation": "base.annotations.search", "target": "base.self_annotation.search@1", "request": "bounded status/limit query", "response": "items envelope -> bounded self annotation projections", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.self_annotation.search": _annotation_search'},
    ("PUT", "/api/self_ann/{dynamic}"): {"operation": "base.annotations.apply", "target": "base.self_annotation.change.apply@1", "request": "item gid/revision/typed attachment references -> closed idempotent command", "response": "annotation envelope -> closed annotation projection", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.self_annotation.change.apply": _annotation_change'},
    ("GET", "/api/users/me"): {"operation": "base.identity.session.profile.get", "target": "base.identity.session.profile.get@1", "request": "current actor -> empty closed input", "response": "closed identity projection without credential or token fields", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.identity.session.profile.get": _identity_profile'},
    ("POST", "/api/plugin/install"): {"operation": "base.plugins.install", "target": "base.plugin.installation.request.create@1", "request": "signed release identity/hash and explicit grants -> closed tenant-bound install command", "response": "installation envelope -> disabled signed-release projection", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.plugin.installation.request.create": _plugin_install'},
    ("DELETE", "/api/plugin/uninstall/{dynamic}"): {"operation": "base.plugins.uninstall", "target": "base.plugin.installation.transition.uninstall@1", "request": "plugin id/revision -> explicit confirmed recoverable uninstall command", "response": "installation envelope -> uninstalled projection with revoked grants", "provider_source": "backend/base/web_atomic.py", "provider_needle": '"base.plugin.installation.transition.uninstall": _plugin_uninstall'},
}


def _review(
    route: str,
    target: str,
    candidate_source: str,
    candidate_needle: str,
    reason_code: str,
    followup: str,
    input_difference: str,
    output_difference: str,
    side_effect_difference: str,
) -> dict[str, Any]:
    return {
        "target": target,
        "reason_code": reason_code,
        "followup": followup,
        "candidate_source": candidate_source,
        "candidate_needle": candidate_needle,
        "contract_mismatch": {
            "input": f"{route}: {input_difference}",
            "output": f"{route}: {output_difference}",
            "side_effects": f"{route}: {side_effect_difference}",
        },
    }


_BASE = "backend/base/reviewed_capabilities.py"
_COLLAB = "backend/base/collaboration.py"
_SHARED = "backend/capabilities/system_shared_next.py"
_PLUGIN = "backend/capabilities/plugin_marketplace_next.py"
_INTEGRATION = "plugins/integration/integration_backend/capabilities/descriptors.py"
_RULE_ENGINE = "plugins/craft/craft_backend/capabilities/rule_engine.py"
_RULE_LIFECYCLE = "plugins/craft/craft_backend/capabilities/rule_descriptors.py"
_AGENT = "plugins/agent/agent_backend/capabilities/contracts.py"
_PROJECT = "plugins/project_management/project_management_backend/application/service.py"

RECLASSIFICATIONS: dict[tuple[str, str], dict[str, Any]] = {
    ("DELETE", "/api/grants/{dynamic}"): _review("/api/grants/{dynamic}", "base.authorization.grant.change.apply@1", _BASE, "base.authorization.grant.change.apply", "provider_equivalence_missing", "provider_adapter_review", "REST deletes one grant gid; candidate accepts generic operation/resource.", "REST returns deletion success; candidate returns generic result.", "Candidate BaseOutcomePort is unbound and cannot perform the legacy delete."),
    ("GET", "/api/ext-datasources"): _review("/api/ext-datasources", "integration.connector.search@1", _INTEGRATION, '"integration.connector.search"', "contract_shape_mismatch", "atomic_capability_review", "REST query uses legacy datasource filters; candidate binds actor/team and connector search payload.", "REST returns datasource rows; candidate returns connector items projection.", "Candidate applies Integration ownership scoping absent from the legacy projection."),
    ("GET", "/api/ext-datasources/{dynamic}/tables"): _review("/api/ext-datasources/{dynamic}/tables", "integration.connector.schema.discover@1", _INTEGRATION, '"integration.connector.schema.discover"', "contract_shape_mismatch", "atomic_capability_review", "REST uses datasource gid and table listing semantics; candidate requires connector gid discovery contract.", "REST returns table names; candidate returns connector-runtime schema discovery projection.", "Candidate performs bounded external discovery and network policy checks."),
    ("GET", "/api/ext-field-mappings"): _review("/api/ext-field-mappings", "integration.field_mapping.search@1", _INTEGRATION, '"integration.field_mapping.search"', "contract_shape_mismatch", "atomic_capability_review", "REST lists legacy field mappings; exact candidate requires one owned mapping gid and a bounded limit.", "Both return a collection; candidate returns closed field identities and revisions.", "Candidate enforces actor/team ownership through one bounded collection query."),
    ("GET", "/api/ext-mappings"): _review("/api/ext-mappings", "integration.mapping.search@1", _INTEGRATION, '"integration.mapping.search"', "contract_shape_mismatch", "atomic_capability_review", "REST uses legacy datasource/mapping filters; candidate uses bounded owned mapping search.", "REST returns legacy mapping records; candidate returns Integration mapping items.", "Candidate binds actor/team ownership."),
    ("GET", "/api/ext-mappings/{dynamic}/columns"): _review("/api/ext-mappings/{dynamic}/columns", "integration.mapping.source_columns.discover@1", _INTEGRATION, '"integration.mapping.source_columns.discover"', "contract_shape_mismatch", "atomic_capability_review", "Both start from a mapping gid; candidate additionally binds its owned connector and caps results.", "Both return source columns; candidate uses a closed bounded projection.", "Candidate invokes the bounded connector runtime through the owned mapping."),
    ("GET", "/api/ext-mappings/{dynamic}/preview"): _review("/api/ext-mappings/{dynamic}/preview", "integration.mapping.preview@1", _INTEGRATION, '"integration.mapping.preview"', "contract_shape_mismatch", "atomic_capability_review", "REST preview parameters and legacy mapping shape differ from candidate gid contract.", "REST returns legacy preview rows; candidate returns runtime preview evidence.", "Candidate invokes connector runtime and ownership/network controls."),
    ("GET", "/api/grants"): _review("/api/grants", "base.authorization.grant.read@1", _BASE, "base.authorization.grant.read", "provider_equivalence_missing", "provider_adapter_review", "REST supports grant list filters; candidate exposes generic reviewed payload.", "REST returns grant rows; candidate generic result has no proved projection.", "Candidate BaseOutcomePort is unbound."),
    ("GET", "/api/notifications/prefs"): _review("/api/notifications/prefs", "base.notification.preference.get@1", _COLLAB, '"base.notification.preference.get"', "state_model_mismatch", "provider_adapter_review", "REST reads legacy user preference columns; candidate keys versioned collaboration state by tenant/user.", "REST returns flat preferences; candidate returns {version,preferences}.", "Candidate uses collaboration service state rather than legacy user storage."),
    ("GET", "/api/org/teams"): _review("/api/org/teams", "base.team.read@1", _BASE, "base.team.read", "provider_equivalence_missing", "provider_adapter_review", "REST applies organisation-specific filters; candidate has generic reviewed payload.", "REST returns organisation team rows; candidate projection is unproved.", "Candidate BaseOutcomePort is unbound."),
    ("GET", "/api/rule-engine/check-entry"): _review("/api/rule-engine/check-entry", "craft.rule.engine.evaluate@1", _RULE_ENGINE, 'id="craft.rule.engine.evaluate"', "outcome_mismatch", "atomic_capability_review", "REST accepts entry audit query; candidate requires operation plus rule/context or version.", "REST returns entry check findings; candidate returns evaluate/audit outcome.", "Candidate evaluates CEL or bounded BOP audit, not the legacy entry check."),
    ("GET", "/api/self_ann/batch"): _review("/api/self_ann/batch", "base.annotation.read@1", _BASE, "base.annotation.read", "provider_equivalence_missing", "provider_adapter_review", "REST batch reads multiple annotated objects; candidate has generic reviewed payload.", "REST returns keyed batch annotations; candidate generic result is unproved.", "Candidate BaseOutcomePort is unbound."),
    ("GET", "/api/teams"): _review("/api/teams", "base.team.read@1", _BASE, "base.team.read", "provider_equivalence_missing", "provider_adapter_review", "REST team list query differs from generic candidate payload.", "REST returns full team records; candidate projection is unproved.", "Candidate BaseOutcomePort is unbound."),
    ("GET", "/api/users"): _review("/api/users", "identity.principal.search@1", _SHARED, '"identity.principal.search"', "projection_mismatch", "atomic_capability_review", "REST admin list supports role/status/paging; candidate accepts query and bounded limit.", "REST returns full administrative users; candidate returns bounded principal summaries.", "Candidate composes registered identity providers and truncates at limit."),
    ("GET", "/api/users/search"): _review("/api/users/search", "identity.principal.search@1", _SHARED, '"identity.principal.search"', "projection_mismatch", "atomic_capability_review", "REST user search supports legacy fields; candidate accepts query and bounded limit.", "REST returns user records; candidate returns bounded principal summaries.", "Candidate composes provider summaries and enforces a hard limit."),
    ("PATCH", "/api/ext-datasources/{dynamic}"): _review("/api/ext-datasources/{dynamic}", "integration.connector.update@1", _INTEGRATION, '"integration.connector.update"', "contract_shape_mismatch", "atomic_capability_review", "REST patch omits mandatory expected_revision and uses legacy datasource fields.", "REST returns patched datasource; candidate returns connector revision projection.", "Candidate validates host/network and optimistic revision."),
    ("PATCH", "/api/notifications/prefs"): _review("/api/notifications/prefs", "base.notification.preference.update@1", _COLLAB, '"base.notification.preference.update"', "state_model_mismatch", "provider_adapter_review", "REST patches flat user columns; candidate requires expected_version and preferences.", "REST returns flat preferences; candidate returns incremented {version,preferences}.", "Candidate writes versioned collaboration state."),
    ("PATCH", "/api/users/{dynamic}/role"): _review("/api/users/{dynamic}/role", "base.identity.role.assign@1", _BASE, "base.identity.role.assign", "provider_equivalence_missing", "provider_adapter_review", "REST assigns role to path user gid; candidate generic operation/resource is unproved.", "REST returns updated user role; candidate generic result is unproved.", "Candidate BaseOutcomePort is unbound."),
    ("POST", "/api/approval/orders/{dynamic}/reject"): _review("/api/approval/orders/{dynamic}/reject", "project.approval.change.apply.atomic.approval_orders_reject@1", _PROJECT, '"approval.orders.reject"', "adapter_side_effect_missing", "bff_review", "REST path/body is transformed to approval reject arguments.", "Both return the rejected order, but REST also consumes notification data.", "REST adapter publishes the returned applicant notification; direct atomic invocation does not compose that publication."),
    ("POST", "/api/ext-datasources"): _review("/api/ext-datasources", "integration.connector.create@1", _INTEGRATION, '"integration.connector.create"', "contract_shape_mismatch", "atomic_capability_review", "REST legacy datasource body differs from required connector_type/host/credential_ref contract.", "REST returns datasource row; candidate returns owned connector projection.", "Candidate validates network policy and credential reference."),
    ("POST", "/api/ext-datasources/{dynamic}/test"): _review("/api/ext-datasources/{dynamic}/test", "integration.connector.connection.test@1", _INTEGRATION, '"integration.connector.connection.test"', "contract_shape_mismatch", "atomic_capability_review", "REST test body/path differs from candidate connector gid payload.", "REST returns legacy connection result; candidate returns connector-runtime evidence.", "Candidate invokes bounded external runtime and network policy."),
    ("POST", "/api/ext-mappings"): _review("/api/ext-mappings", "integration.mapping.create@1", _INTEGRATION, '"integration.mapping.create"', "contract_shape_mismatch", "atomic_capability_review", "REST mapping body omits target capability/catalog fields required by candidate.", "REST returns legacy mapping row; candidate returns governed mapping projection.", "Candidate validates restricted transforms and ownership."),
    ("POST", "/api/ext-mappings/{dynamic}/import"): _review("/api/ext-mappings/{dynamic}/import", "integration.mapping.import.start@1", _INTEGRATION, '"integration.mapping.import.start"', "contract_shape_mismatch", "atomic_capability_review", "REST performs a synchronous import; exact candidate accepts mapping_gid plus durable idempotency.", "Candidate returns a durable run_id and operation_ref instead of synthetic completion.", "Candidate records accepted/outcome_unknown and reconciles retries without repeating the side effect."),
    ("POST", "/api/grants"): _review("/api/grants", "base.authorization.grant.change.apply@1", _BASE, "base.authorization.grant.change.apply", "provider_equivalence_missing", "provider_adapter_review", "REST creates a concrete grant body; candidate generic operation/resource is unproved.", "REST returns created grant; candidate generic result is unproved.", "Candidate BaseOutcomePort is unbound."),
    ("POST", "/api/org/sync-from-feishu"): _review("/api/org/sync-from-feishu", "base.identity.directory.sync@1", _BASE, "base.identity.directory.sync", "provider_equivalence_missing", "provider_adapter_review", "REST starts Feishu-specific directory sync; candidate generic payload is unproved.", "REST returns Feishu sync counts; candidate generic result is unproved.", "Candidate BaseOutcomePort is unbound and has no Feishu adapter."),
    ("POST", "/api/rules/{dynamic}/activate"): _review("/api/rules/{dynamic}/activate", "craft.rule.release.activate@1", _RULE_LIFECYCLE, '"craft.rule.release.activate"', "outcome_mismatch", "atomic_capability_review", "REST activates mutable rule gid; candidate activates a published immutable release contract.", "REST returns rule status; candidate returns accepted release outcome.", "Candidate lifecycle handler does not mutate the legacy rule record."),
    ("POST", "/api/rules/{dynamic}/deviations"): _review("/api/rules/{dynamic}/deviations", "craft.rule.waiver.create@1", _RULE_LIFECYCLE, '"craft.rule.waiver.create"', "outcome_mismatch", "atomic_capability_review", "REST deviation body is tied to rule gid; candidate waiver contract expects governed release/evidence fields.", "REST returns deviation record; candidate returns accepted waiver outcome.", "Candidate does not persist the legacy deviation model."),
    ("POST", "/api/skills/execute-canvas"): _review("/api/skills/execute-canvas", "agent.run.change.apply@1", _AGENT, '"agent.run.change.apply"', "outcome_mismatch", "atomic_capability_review", "REST accepts canvas/flow inputs and execution mode; candidate run change contract uses run resource operations.", "REST returns canvas execution and pause token; candidate returns run resource projection.", "Candidate does not execute the legacy skill canvas orchestration."),
    ("POST", "/api/skills/resume-canvas"): _review("/api/skills/resume-canvas", "agent.run.change.apply@1", _AGENT, '"agent.run.change.apply"', "outcome_mismatch", "atomic_capability_review", "REST accepts pause token/resume inputs; candidate run change contract uses run resource operations.", "REST returns resumed canvas execution; candidate returns run resource projection.", "Candidate has no pause-token resume side effect."),
    ("PUT", "/api/ext-field-mappings/batch"): _review("/api/ext-field-mappings/batch", "integration.field_mapping.batch.update@1", _INTEGRATION, '"integration.field_mapping.batch.update"', "contract_shape_mismatch", "atomic_capability_review", "Both batch-update one mapping; exact candidate requires revision, confirmation, and idempotency.", "Both return batch count/items; candidate returns deterministic field identities and revisions.", "Candidate commits the all-or-nothing batch with its idempotent result and audit evidence."),
    ("PUT", "/api/rules/{dynamic}"): _review("/api/rules/{dynamic}", "craft.rule.library.change.apply@1", "plugins/craft/craft_backend/capabilities/contracts.py", 'INPUT_SCHEMAS[("craft.rule.library.change.apply", 1)]', "contract_shape_mismatch", "atomic_capability_review", "REST accepts a non-empty update record; the published stable candidate closes record with no allowed properties.", "REST returns the updated rule projection; the candidate cannot be invoked with any meaningful update record.", "REST reaches the rule provider with one of its ten supported fields; the Gateway rejects that same non-empty record before provider execution."),
}

REVIEWED_DECISIONS = {
    **{key: {**value, "decision": "migrate"} for key, value in MIGRATIONS.items()},
    **{key: {**value, "decision": "reclassify"} for key, value in RECLASSIFICATIONS.items()},
}

if len(REVIEWED_DECISIONS) != 53:
    raise RuntimeError("Task 3B.3b reviewed decision total drift")

__all__ = ["BASELINE_REVISION", "MIGRATIONS", "RECLASSIFICATIONS", "REVIEWED_DECISIONS"]
