<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>AI00.ConnectorHost</AssemblyName>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ai00.Connector.Tests" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <ProjectReference Include="..\Ai00.Connector.Contracts.V2\Ai00.Connector.Contracts.V2.csproj" />
    <ProjectReference Include="..\Ai00.Connector.Adapters.VisMockup\Ai00.Connector.Adapters.VisMockup.csproj" />
  </ItemGroup>
</Project>
